### ISSUE TITLE
Getting nil matrices object in connector's TryInitState method

### ISSUE THREAD

**Issue by darshan-lukhi** [hasura/ndc-sdk-go#96]
I encountered a nil metrics object in the `TryInitState` method. Since this nil object prevents us from adding matrices or we need to reinitialise telemetry which is not an good idea.

Issue is due to passing nil matrices in `TryInitState`
https://github.com/hasura/ndc-sdk-go/blob/80eff226f35cf8dd1d63e118d7fe429e57dfbde2/connector/server.go#L72

Here is the fix for this issue
```go
	telemetry, err := setupOTelSDK(ctx, &options.OTLPConfig, defaultOptions.version, defaultOptions.metricsPrefix, defaultOptions.logger)
	if err != nil {
		return nil, err
	}
	
	state, err := connector.TryInitState(ctx, configuration, telemetry)
	if err != nil {
		return nil, err
	}
```

**Comment by hgiasac** [comment]
Oops, my bad. Thanks for reporting. Will fix soon

**Comment by hgiasac** [comment]
@darshan-lukhi can you please upgrade the SDK v1.1.4 to verify? Thanks
